### ISSUE TITLE
Create Issue Template

### ISSUE THREAD

**Issue by muthuannamalai12** [harshsbais/Amazon-Price-Drop-Alert#18]
Hai,
I would love to add an issue template for your repository. This template would have four issues namely bug, documentation, feature, proposal and question

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of DWOC. Kindly assign it to me

**Comment by harshsbais** [comment]
yes go ahead

**Comment by muthuannamalai12** [comment]
I have created a pull request. Kindly review it
