### ISSUE TITLE
README FILE BADGES IMPROVE

### ISSUE THREAD

**Issue by akrish4** [harshsbais/Amazon-Price-Drop-Alert#19]
Hi @harshsbais 
There are no badges or shields in the readme file , Kindly assign me if you would like to see more badges in it 
I would be glad to work on it pls bro 

![readme1](https://user-images.githubusercontent.com/61831021/103935432-925f1000-514c-11eb-8e8f-4c5a736ea9c1.PNG)

**Comment by harshsbais** [comment]
yes go ahead.

**Comment by akrish4** [comment]
#23
