### ISSUE TITLE
contributors.md file 

### ISSUE THREAD

**Issue by akrish4** [harshsbais/Amazon-Price-Drop-Alert#24]
## 🚀 Feature

Hi @harshsbais 

I would like to add a contributors file which consists of all contributors aling with their profile picture and name in tabular format 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/harshsbais/Amazon-Price-Drop-Alert/blob/master/CONTRIBUTING.md)?

Yes

## Motivation

self-motivation

## Pitch

So that all contributors get their recognition towards open source contribution as well as everyine will come to know the contributors of this great intiative 

Kindly assign me if you are interested in this and pls add a good label too as my contribution to this repository makes me happy

**Comment by harshsbais** [comment]
Yes sure go ahead

**Comment by akrish4** [comment]
@harshsbais  Kindly pls do assign me this issue

**Comment by akrish4** [comment]
#31  PR
