### ISSUE TITLE
Integrate Welcome and Greeting Bot

### ISSUE THREAD

**Issue by samir-0711** [harshsbais/Amazon-Price-Drop-Alert#27]
## 🚀 Feature

Hi @harshsbais 
I would like to contribute to this project by adding a welcome and greeting bot which will comment up when any user will open up with an issue or pull-request for the first time
( config file having a proper message)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/harshsbais/Amazon-Price-Drop-Alert/blob/master/CONTRIBUTING.md)?

Yes

For reference, kindly check out: https://github.com/apps/welcome

**Comment by samir-0711** [comment]
I would like to work on this.

**Comment by shrutijha16** [comment]
can i work on this issue?
