### ISSUE TITLE
Readme updation

### ISSUE THREAD

**Issue by Sloth-Panda** [harshsbais/Amazon-Price-Drop-Alert#29]
Readme can be updated by adding various open-source programs this project is a part of and also gifs will make it interesting. let me know

**Comment by harshsbais** [comment]
ya sure go ahead

**Comment by achalesh27022003** [comment]
@harshsbais sir I'm ready to take the issue. Please assign me.

**Comment by harshsbais** [comment]
> @harshsbais sir I'm ready to take the issue. Please assign me.

yes sure go ahead
