### ISSUE TITLE
NO DIRECT LINKS TO README 

### ISSUE THREAD

**Issue by akrish4** [harshsbais/Amazon-Price-Drop-Alert#32]
## 🐛 Bug Report

There is no direct links of `CODE OF CONDUCT` file and `CONTRIBUTING` guidelines in the readme file 
Kindly do assign me 
I can add the direct links so users can directly click in it and they can read it 
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/harshsbais/Amazon-Price-Drop-Alert/blob/master/CONTRIBUTING.md)?

(Write your answer here.)
yes

**Comment by harshsbais** [comment]
yes sure go ahead
